[project]
name = "bb-bt-codes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bposd",
    "ldpc",
    "matplotlib",
    "mypy",
    "networkx",
    "numpy",
    "pytest",
    "scipy",
    "stim",
]
